-- -- table creation process for matches.csv

CREATE TABLE matches (
	MATCH_ID varchar(6) NOT NULL PRIMARY KEY,
	SEASON varchar(10) NOT NULL,
	EVENT_DATE VARCHAR(20) NOT NULL,
	HOME_TEAM varchar(30) NOT NULL,
	AWAY_TEAM varchar(30) NOT NULL,
	STADIUM varchar(30) NOT NULL,
	HOME_TEAM_SCORE INT NOT NULL,
	AWAY_TEAM_SCORE INT NOT NULL,
	PENALTY_SHOOT_OUT INT NOT NULL,
	ATTENDANCE INT NOT NULL
);

COPY matches(MATCH_ID, SEASON, EVENT_DATE, HOME_TEAM, AWAY_TEAM, STADIUM, HOME_TEAM_SCORE, AWAY_TEAM_SCORE, PENALTY_SHOOT_OUT, ATTENDANCE)
FROM 'N:/Data Analyst/SQL_final_capstone_project/Matches.csv'
DELIMITER ','
CSV HEADER;

select * from matches;


